### ISSUE TITLE
[Feature] using CF

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team4#112]
collaborative filtering을 실제로 frontend에서 사용해야 한다.
과목 검색이나 recommendation에서 사용되며
과목 검색에서는 점수 순으로 정렬
recommendation에서는 유저가 자신이 준 점수를 확인/ 수정할 수 있어야 한다.

**Comment by vionicbest** [comment]
detail searching 부분에 cf가 연결되었고 recommend부분에도 연결되었으므로 확인되면 닫아주세요
