### ISSUE TITLE
[Feature] Searching detail

### ISSUE THREAD

**Issue by 1207koo** [swsnu/swpp2019-team4#113]
과목 검색 시 더 자세한 정보로 검색할 수 있어야 한다.
예를 들면 학점 수나 교수님 성함으로도 과목을 검색할 수 있도록 해야 한다.
(현재는 과목 이름으로만 검색 가능)

**Comment by vionicbest** [comment]
필터를 달 수 있고 collaborative filtering을 통해 과목을 보여주는 feature가 구현되었으므로 닫겠습니다
