### ISSUE TITLE
[Bug] Pending search query

### ISSUE THREAD

**Issue by cube-c** [swsnu/swpp2019-team4#117]
* 검색을 계속해서 누를 경우 쿼리 여러 개가 pending되는 문제를 해결하는 것이 필요함
* 한 번 검색 후 쿼리가 도달할 때까지 검색 버튼을 비활성화시키는 것도 하나의 방법

**Comment by vionicbest** [comment]
server protection branch가 위를 커버하고 있습니다 #123 닫겠습니다
