### ISSUE TITLE
[User testing feedback] Department

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team4#129]
가능한 Department 후보를 모르겠습니다.
경영학과라고 쳤는데 존재하는 학과를 치라고 나왔습니다.

**Comment by 1207koo** [comment]
아직은 컴퓨터공학부만 가능합니다

**Comment by haesookim** [comment]
매번 text matching을 하는 것보다 자유응답으로 두는 게 낫지 않을까요? 예를 들어 컴퓨터공학부 또한 컴공/컴퓨터공학과/컴퓨터공학 이런 다양한 응답이 있을 수 있을 테니까요! (제안입니다ㅎㅎ)

**Comment by 1207koo** [comment]
그래서 아직은 텍스트 입력이지만
가능한 과를 리스트로 보여주고 거기서 선택할 수 있도록 할 예정입니다.

**Comment by cube-c** [comment]
Closed. Issue #144
