### ISSUE TITLE
기능에 대한 설명 

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team4#132]
![image](https://user-images.githubusercontent.com/33143827/70226062-8065ad80-1793-11ea-95c6-af4bf51c32d8.png)
해당 기능이 무엇을 의미하는 지 잘 모르겠습니다. ㅠㅠ
10분이라는 시간이 파악하기 짧아서 그런 걸 수도 있지만 어떤 방법으로 사용하면 좋을 지 안내해주시면 감사하겠습니다!

**Comment by iamsungyeonjoo** [comment]
그리고 드래그 하고 나서 지우는 것은 어떻게 하는 건가요?

**Comment by 1207koo** [comment]
수업을 듣고 싶은 시간과 듣기 싫은 시간을 선택하는 곳입니다.
오른쪽 색깔들에서 색을 선택하고
시간표에서 색칠하면 됩니다.
지우는 것은 흰색으로 그리면 됩니다.

**Comment by iamsungyeonjoo** [comment]
![image](https://user-images.githubusercontent.com/33143827/70226372-1994c400-1794-11ea-9f1f-17638ff44136.png)
이 부분의 학점 범위는 무슨 의미인가요? 15학점인 걸 봐서.. 15학점짜리 수업이 있을리는 없는데 무슨 의미인지 알고 싶습니다!
