### ISSUE TITLE
메일 인증이 안와요

### ISSUE THREAD

**Issue by HaeTheong** [swsnu/swpp2019-team4#137]
platina47@snu.ac.kr로 가입했는데
메일도 안오고 이미 있는 메일이라고 재가입도 안되네요..ㅜㅜ

**Comment by vionicbest** [comment]
verification email이 느리게 올 수도 있습니다. 외부 메일서버를 사용해서... ㅠ 죄송합니다

**Comment by 1207koo** [comment]
재가입이 안되는 것은 인증 메일 보내는 절차로 넘어가서 그렇고
사람이 많아서 메일이 늦게 보내지는 것 같습니다. 죄송합니다

**Comment by HaeTheong** [comment]
지금 왔네요 감사합니다 :)
