### ISSUE TITLE
빨간색 줄이 없어지면 더 좋을 것 같습니다.

### ISSUE THREAD

**Issue by iamsungyeonjoo** [swsnu/swpp2019-team4#138]
![image](https://user-images.githubusercontent.com/33143827/70226218-cfabde00-1793-11ea-9262-50b440cf6c20.png)
밑에 보이는 빨간색 줄이 특별한 의미가 있나요?
없다면 안보이는게 더 좋을 것 같습니다.

수고하세요! :)

**Comment by cube-c** [comment]
현재 시간을 나타내는 줄입니다.

**Comment by cube-c** [comment]
Closed. Issue #145
