### ISSUE TITLE
[Request] Detailed information page of a course

### ISSUE THREAD

**Issue by cube-c** [swsnu/swpp2019-team4#38]
Timetable management page, main page 등에서 특정 과목을 클릭했을 때, 그 과목의 자세한 정보를 볼 수 있는 창을 띄울 수 있도록 하는 기능이 있으면 좋을 것 같다.

Trigger:

* page에 있는 timetable의 과목 중 하나를 클릭

Event:

* 후보 1 : 새로운 페이지에 과목에 관한 세부 정보 소개
* 후보 2 : 팝업 창(e.g. SNULife 강의실+)으로 과목 세부 정보 소개

**Comment by 1207koo** [comment]
수강신청 사이트에서 자세한 과목 정보를 띄우는 것이 있다.
링크의 정확한 규칙을 알지는 못하지만
강의 번호만으로 링크값을 알 수 있는 것으로 추정된다.
따라서 new tab으로 그 링크를 열어주는 것으로 해결될 수 있을 것이라 예상된다.
