### ISSUE TITLE
[Request] Replace Alert

### ISSUE THREAD

**Issue by cube-c** [swsnu/swpp2019-team4#41]
https://sonarcloud.io/project/issues?id=swsnu_swpp2019-team4&resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=VULNERABILITY

According to SonarCloud, alert function is not secure. It is neccessary to replace this function.

**Comment by vionicbest** [comment]
좀 더 자세한 정보를 기입한 Issue #45 를 올렸으므로 이 issue는 닫습니다
